
item_drop_ratio: 0.2
item_drop_coefficient: 0.9
lambda: 1e-3
plm_size: 768
n_layers: 2
n_heads: 2

hidden_size: 300
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
